Install latest versions of rlang/vctrs for R 3.3.0.
I had pinned them to older versions back when I was still
attempting to test on R 3.2.5. Now I get the error:

Error: namespace 'vctrs' 0.3.4 is being loaded, but >= 0.3.8 is required

https://app.circleci.com/pipelines/github/workflowr/workflowr-pkg-tests/193/workflows/eb0f80b6-959e-4996-bf83-9c3632b903be/jobs/1545
https://circle-production-customer-artifacts.s3.amazonaws.com/picard/5d387596d421683e294c96af/60b5904ed537c676217d2434-0-build/artifacts/tmp/workflowr/workflowr.Rcheck/tests/testthat.Rout.fail?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210601T154644Z&X-Amz-SignedHeaders=host&X-Amz-Expires=60&X-Amz-Credential=AKIAJR3Q6CR467H7Z55A%2F20210601%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=6b2284f78b3948526295e39f46350b4b629cc84b1545182a829a0972d1804050

Since I bumped it to R 3.3.0, I should be able to install the
latest versions directly from CRAN.

Note that I tried to split the installation line, but I couldn't
get the formatting to work. Presumably \ can't continue a line
within single quotes.