Install libpng-dev for reticulate which now depends on png.
png was added as a dependency to the dev version of reticulate
only 28 days ago.

https://github.com/rstudio/reticulate/commit/4967abddb35865a1be6ad839298695f1481bcade

Downloading GitHub repo rstudio/reticulate@HEAD
png (NA -> 0.1-7) [CRAN]
Installing 1 packages: png
Installing package into ‘/root/R/Library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/png_0.1-7.tar.gz'
Content type 'application/x-gzip' length 24990 bytes (24 KB)
==================================================
downloaded 24 KB

* installing *source* package ‘png’ ...
** package ‘png’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include   `libpng-config --cflags` -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c read.c -o read.o
/bin/bash: libpng-config: command not found
read.c:3:10: fatal error: png.h: No such file or directory
    3 | #include <png.h>
      |          ^~~~~~~
compilation terminated.
make: *** [/usr/local/lib/R/etc/Makeconf:168: read.o] Error 1
ERROR: compilation failed for package ‘png’
* removing ‘/root/R/Library/png’

https://app.circleci.com/pipelines/github/workflowr/workflowr-pkg-tests/180/workflows/57f69ab0-bbe7-4ea6-93d9-0e6042984156/jobs/1433